### ISSUE TITLE
bug: unable to access the API via IP address.

### ISSUE THREAD

**Issue by cheny-alf** [superproj/onex#12]
#### What happened:
When I deployed it on the server via a container and tried to test the API using the IP address, I encountered the error `Error: connect ECONNREFUSED IP:50843`
#### What you expected to happen:
The API can be accessed normally.
#### How to reproduce it (as minimally and precisely as possible):
1. make docker-install
2. curl --location 'http://IP:50843/v1/users?offset=0&limit=10' \
--header 'Accept-Language: en' \
--header 'Authorization: Bearer {{refresh_token}}' \
--data ''

**Comment by cheny-alf** [comment]
I believe this is the reason: https://developer.baidu.com/article/details/2812523.
so, I am trying to create a pr 🤔

**Comment by colin404** [comment]
checked, ONEX_ACCESS_HOST config in `ONEX_ACCESS_HOST` and `manifests/env.local.extendvar` is the right value, so close this issue
