### ISSUE TITLE
bug: package go/version is not in std (/usr/local/go/src/go/version)

### ISSUE THREAD

**Issue by cubxxw** [superproj/onex#2]
My go version is 1.22.0, but I use go test./...Report an error

```
smile@smile:/data/workspaces/onex$ go test ./...
/home/smile/go/pkg/mod/golang.org/x/tools@v0.16.1/internal/versions/versions_go122.go:11:2: package go/version is not in std (/usr/local/go/src/go/version)
```

I think:

Your project is trying to use some of the features or dependencies of Go 1.21.5, but the Go toolchain version you installed is 1.22.0.Such version inconsistencies can cause compilation failures or other problems.

**Comment by colin404** [comment]
not a bug. my caused by go environment. 

`go env|grep GOROOT`  and check is go/version is in the output path
